// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgvivjtprovodtzonaej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRndml2anRwcm92b2R0em9uYWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExOTc1MDksImV4cCI6MjA4Njc3MzUwOX0.UI0XWgWGVnKC5yu0G08trckltTrmKHNMfNC30g1pCO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});